// Generated by CoffeeScript 1.6.1
(function() {

  test("one tautology", function() {
    return ok(true);
  });

  module("simple tests");

  test("increments", function() {
    var mike;
    mike = 0;
    ok(mike++ === 0);
    return ok(mike === 1);
  });

  test("increments (improved)", function() {
    var mike;
    mike = 0;
    equal(mike++, 0);
    return equal(mike, 1);
  });

  module("setUp/tearDown", {
    setup: function() {},
    teardown: function() {}
  });

  test("example", function() {});

  module("async");

  test("multiple async", function() {
    expect(2);
    stop();
    setTimeout(function() {
      ok(true, "async operation completed");
      return start();
    }, 500);
    stop();
    return setTimeout(function() {
      ok(true, "async operation completed");
      return start();
    }, 500);
  });

}).call(this);
