// Generated by CoffeeScript 1.6.1
(function() {

  require.config({
    deps: ["../vendor/jam/require.config", "main"],
    paths: {
      "lodash": "../vendor/jam/lodash/lodash.underscore"
    },
    map: {
      "*": {
        "underscore": "lodash"
      }
    },
    shim: {}
  });

}).call(this);
