// Generated by CoffeeScript 1.6.1
(function() {

  define(["app"], function(app) {
    var Router;
    Router = Backbone.Router.extend({
      routes: {
        "": "index"
      },
      index: function() {}
    });
    return Router;
  });

}).call(this);
