// Generated by CoffeeScript 1.6.1
(function() {

  module.exports = function(grunt) {
    grunt.initConfig({
      lint: {
        files: ["build/config.js", "app/**/*.js"]
      },
      jshint: {
        options: {
          scripturl: true
        }
      },
      jst: {
        "dist/debug/templates.js": ["app/templates/**/*.html"]
      },
      styles: {
        "dist/debug/index.css": {
          src: "app/styles/index.css",
          paths: ["app/styles"],
          prefix: "app/styles/",
          additional: []
        }
      },
      requirejs: {
        mainConfigFile: "app/config.js",
        jamConfig: "/vendor/jam/require.config.js",
        out: "dist/debug/require.js",
        name: "config",
        wrap: false
      },
      concat: {
        dist: {
          src: ["vendor/js/libs/almond.js", "dist/debug/templates.js", "dist/debug/require.js"],
          dest: "dist/debug/require.js",
          separator: ";"
        }
      },
      mincss: {
        "dist/release/index.css": ["dist/debug/index.css"]
      },
      min: {
        "dist/release/require.js": ["dist/debug/require.js"]
      },
      server: {
        files: {
          "favicon.ico": "favicon.ico"
        },
        prefix: "app/styles/",
        debug: {
          files: "<config:server.files>",
          folders: {
            "app": "dist/debug",
            "vendor/js/libs": "dist/debug",
            "app/styles": "dist/debug"
          }
        },
        release: {
          host: "0.0.0.0",
          files: "<config:server.files>",
          folders: {
            "app": "dist/release",
            "vendor/js/libs": "dist/release",
            "app/styles": "dist/release"
          }
        }
      },
      qunit: {
        all: ["test/qunit/*.html"]
      },
      jasmine: {
        all: ["test/jasmine/*.html"]
      },
      watch: {
        files: ["grunt.js", "vendor/**/*", "app/**/*"],
        tasks: "styles"
      },
      clean: ["dist/"]
    });
    grunt.registerTask("debug", "clean lint jst requirejs concat styles");
    return grunt.registerTask("release", "debug min mincss");
  };

}).call(this);
